import type { Metadata } from "next";
import Navbar from "../components/Navbar/page";
import "./globals.css";
import { ThemeProvider } from "@/components/themes-provider";
import { Footer } from "@/components/Footer/page";
import { AuthProvider } from "@/components/context/AuthContext";
import { AuthProviderWrapper } from "@/components/context/authProviderWrapper";
import { ModeToggle } from "@/components/mode-toggle";
import { WSProvider } from "@/components/context/wsContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased flex flex-col min-h-screen overflow-y-auto scrollbar-hidden">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Wrap in AuthProvider */}
          <AuthProvider>
            <AuthProviderWrapper>
              {/* Wrap in WebSocket provider */}
              <WSProvider>
                <ModeToggle />
                <Navbar />
                <main className="flex-1">{children}</main>
                <Footer />
              </WSProvider>
            </AuthProviderWrapper>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
